// Mocks generated by Mockito 5.4.6 from annotations
// in codium/test/features/pdf_reader/view/pdf_reader_text_selection_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:codium/domain/models/ai_explanation/explanation.dart' as _i7;
import 'package:codium/domain/models/pdf_library/pdf_book.dart' as _i4;
import 'package:codium/domain/models/pdf_reader/bookmark.dart' as _i5;
import 'package:codium/domain/repositories/pdf_repository.dart' as _i2;
import 'package:codium/domain/repositories/storage_repository.dart' as _i6;
import 'package:codium/domain/usecases/save_bookmark_usecase.dart' as _i9;
import 'package:codium/domain/usecases/update_reading_progress_usecase.dart'
    as _i8;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [IPdfRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIPdfRepository extends _i1.Mock implements _i2.IPdfRepository {
  MockIPdfRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.PdfBook>> getAllBooks() =>
      (super.noSuchMethod(
            Invocation.method(#getAllBooks, []),
            returnValue: _i3.Future<List<_i4.PdfBook>>.value(<_i4.PdfBook>[]),
          )
          as _i3.Future<List<_i4.PdfBook>>);

  @override
  _i3.Future<_i4.PdfBook?> getBookById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getBookById, [id]),
            returnValue: _i3.Future<_i4.PdfBook?>.value(),
          )
          as _i3.Future<_i4.PdfBook?>);

  @override
  _i3.Future<void> importPdf(String? filePath) =>
      (super.noSuchMethod(
            Invocation.method(#importPdf, [filePath]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updateReadingProgress(String? bookId, int? page) =>
      (super.noSuchMethod(
            Invocation.method(#updateReadingProgress, [bookId, page]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteBook(String? bookId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteBook, [bookId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<_i5.Bookmark>> getBookmarks(String? bookId) =>
      (super.noSuchMethod(
            Invocation.method(#getBookmarks, [bookId]),
            returnValue: _i3.Future<List<_i5.Bookmark>>.value(<_i5.Bookmark>[]),
          )
          as _i3.Future<List<_i5.Bookmark>>);

  @override
  _i3.Future<void> addBookmark(_i5.Bookmark? bookmark) =>
      (super.noSuchMethod(
            Invocation.method(#addBookmark, [bookmark]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteBookmark(String? bookmarkId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteBookmark, [bookmarkId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}

/// A class which mocks [IStorageRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIStorageRepository extends _i1.Mock
    implements _i6.IStorageRepository {
  MockIStorageRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i5.Bookmark>> getBookmarksByPdfId(String? pdfId) =>
      (super.noSuchMethod(
            Invocation.method(#getBookmarksByPdfId, [pdfId]),
            returnValue: _i3.Future<List<_i5.Bookmark>>.value(<_i5.Bookmark>[]),
          )
          as _i3.Future<List<_i5.Bookmark>>);

  @override
  _i3.Future<void> saveBookmark(_i5.Bookmark? bookmark) =>
      (super.noSuchMethod(
            Invocation.method(#saveBookmark, [bookmark]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteBookmark(String? bookmarkId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteBookmark, [bookmarkId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<_i7.Explanation>> getExplanationsByPdfId(String? pdfId) =>
      (super.noSuchMethod(
            Invocation.method(#getExplanationsByPdfId, [pdfId]),
            returnValue: _i3.Future<List<_i7.Explanation>>.value(
              <_i7.Explanation>[],
            ),
          )
          as _i3.Future<List<_i7.Explanation>>);

  @override
  _i3.Future<void> saveExplanation(_i7.Explanation? explanation) =>
      (super.noSuchMethod(
            Invocation.method(#saveExplanation, [explanation]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteExplanation(String? explanationId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteExplanation, [explanationId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<_i7.Explanation>> searchExplanations(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#searchExplanations, [query]),
            returnValue: _i3.Future<List<_i7.Explanation>>.value(
              <_i7.Explanation>[],
            ),
          )
          as _i3.Future<List<_i7.Explanation>>);
}

/// A class which mocks [UpdateReadingProgressUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockUpdateReadingProgressUseCase extends _i1.Mock
    implements _i8.UpdateReadingProgressUseCase {
  MockUpdateReadingProgressUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> execute({
    required String? bookId,
    required int? currentPage,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#execute, [], {
              #bookId: bookId,
              #currentPage: currentPage,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}

/// A class which mocks [SaveBookmarkUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockSaveBookmarkUseCase extends _i1.Mock
    implements _i9.SaveBookmarkUseCase {
  MockSaveBookmarkUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> execute(_i5.Bookmark? bookmark) =>
      (super.noSuchMethod(
            Invocation.method(#execute, [bookmark]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
