// Mocks generated by Mockito 5.4.6 from annotations
// in codium/test/features/pdf_reader/bloc/pdf_reader_performance_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:codium/domain/models/pdf_reader/bookmark.dart' as _i6;
import 'package:codium/domain/usecases/save_bookmark_usecase.dart' as _i5;
import 'package:codium/domain/usecases/update_reading_progress_usecase.dart'
    as _i4;
import 'package:codium/domain/usecases/validate_and_open_pdf_usecase.dart'
    as _i2;
import 'package:codium/features/pdf_reader/domain/pdf_cache_service.dart'
    as _i7;
import 'package:mockito/mockito.dart' as _i1;
import 'package:pdfx/pdfx.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeValidatedPdfResult_0 extends _i1.SmartFake
    implements _i2.ValidatedPdfResult {
  _FakeValidatedPdfResult_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ValidateAndOpenPdfUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockValidateAndOpenPdfUseCase extends _i1.Mock
    implements _i2.ValidateAndOpenPdfUseCase {
  MockValidateAndOpenPdfUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i2.ValidatedPdfResult> execute(String? bookId) =>
      (super.noSuchMethod(
            Invocation.method(#execute, [bookId]),
            returnValue: _i3.Future<_i2.ValidatedPdfResult>.value(
              _FakeValidatedPdfResult_0(
                this,
                Invocation.method(#execute, [bookId]),
              ),
            ),
          )
          as _i3.Future<_i2.ValidatedPdfResult>);
}

/// A class which mocks [UpdateReadingProgressUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockUpdateReadingProgressUseCase extends _i1.Mock
    implements _i4.UpdateReadingProgressUseCase {
  MockUpdateReadingProgressUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> execute({
    required String? bookId,
    required int? currentPage,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#execute, [], {
              #bookId: bookId,
              #currentPage: currentPage,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}

/// A class which mocks [SaveBookmarkUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockSaveBookmarkUseCase extends _i1.Mock
    implements _i5.SaveBookmarkUseCase {
  MockSaveBookmarkUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> execute(_i6.Bookmark? bookmark) =>
      (super.noSuchMethod(
            Invocation.method(#execute, [bookmark]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}

/// A class which mocks [PdfCacheService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPdfCacheService extends _i1.Mock implements _i7.PdfCacheService {
  MockPdfCacheService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.PdfPageImage? getCachedPage(int? pageNumber) =>
      (super.noSuchMethod(Invocation.method(#getCachedPage, [pageNumber]))
          as _i8.PdfPageImage?);

  @override
  void cachePage(int? pageNumber, _i8.PdfPageImage? pageImage) =>
      super.noSuchMethod(
        Invocation.method(#cachePage, [pageNumber, pageImage]),
        returnValueForMissingStub: null,
      );

  @override
  void clearCache() => super.noSuchMethod(
    Invocation.method(#clearCache, []),
    returnValueForMissingStub: null,
  );

  @override
  bool isCached(int? pageNumber) =>
      (super.noSuchMethod(
            Invocation.method(#isCached, [pageNumber]),
            returnValue: false,
          )
          as bool);

  @override
  List<int> getCachedPageNumbers() =>
      (super.noSuchMethod(
            Invocation.method(#getCachedPageNumbers, []),
            returnValue: <int>[],
          )
          as List<int>);

  @override
  void preloadAdjacentPages(int? currentPage, int? totalPages) =>
      super.noSuchMethod(
        Invocation.method(#preloadAdjacentPages, [currentPage, totalPages]),
        returnValueForMissingStub: null,
      );
}
