// Mocks generated by Mockito 5.4.6 from annotations
// in codium/test/data/repositories/ai_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:codium/data/datasources/remote/gemini_datasource.dart' as _i2;
import 'package:codium/data/datasources/remote/search_datasource.dart' as _i5;
import 'package:codium/domain/models/ai_explanation/search_source.dart' as _i6;
import 'package:codium/domain/services/connectivity_service.dart' as _i7;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [GeminiDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockGeminiDataSource extends _i1.Mock implements _i2.GeminiDataSource {
  MockGeminiDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<String> explainText({
    required String? text,
    required String? context,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#explainText, [], {
              #text: text,
              #context: context,
            }),
            returnValue: _i3.Future<String>.value(
              _i4.dummyValue<String>(
                this,
                Invocation.method(#explainText, [], {
                  #text: text,
                  #context: context,
                }),
              ),
            ),
          )
          as _i3.Future<String>);
}

/// A class which mocks [SearchDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockSearchDataSource extends _i1.Mock implements _i5.SearchDataSource {
  MockSearchDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i6.SearchSource>> searchWeb(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#searchWeb, [query]),
            returnValue: _i3.Future<List<_i6.SearchSource>>.value(
              <_i6.SearchSource>[],
            ),
          )
          as _i3.Future<List<_i6.SearchSource>>);
}

/// A class which mocks [IConnectivityService].
///
/// See the documentation for Mockito's code generation for more information.
class MockIConnectivityService extends _i1.Mock
    implements _i7.IConnectivityService {
  MockIConnectivityService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isConnected =>
      (super.noSuchMethod(Invocation.getter(#isConnected), returnValue: false)
          as bool);

  @override
  _i3.Stream<bool> get connectivityStream =>
      (super.noSuchMethod(
            Invocation.getter(#connectivityStream),
            returnValue: _i3.Stream<bool>.empty(),
          )
          as _i3.Stream<bool>);
}
