// Mocks generated by Mockito 5.4.6 from annotations
// in codium/test/data/repositories/pdf_repository_file_validation_property_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:codium/data/datasources/local/bookmark_local_datasource.dart'
    as _i6;
import 'package:codium/data/datasources/local/pdf_local_datasource.dart' as _i3;
import 'package:codium/domain/models/pdf_library/pdf_library.dart' as _i5;
import 'package:codium/domain/models/pdf_reader/pdf_reader.dart' as _i7;
import 'package:mockito/mockito.dart' as _i1;
import 'package:talker/talker.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeTalkerSettings_0 extends _i1.SmartFake
    implements _i2.TalkerSettings {
  _FakeTalkerSettings_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTalkerFilter_1 extends _i1.SmartFake implements _i2.TalkerFilter {
  _FakeTalkerFilter_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [PdfLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockPdfLocalDataSource extends _i1.Mock
    implements _i3.PdfLocalDataSource {
  MockPdfLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i5.PdfBook>> getAllBooks() =>
      (super.noSuchMethod(
            Invocation.method(#getAllBooks, []),
            returnValue: _i4.Future<List<_i5.PdfBook>>.value(<_i5.PdfBook>[]),
          )
          as _i4.Future<List<_i5.PdfBook>>);

  @override
  _i4.Future<_i5.PdfBook?> getBookById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getBookById, [id]),
            returnValue: _i4.Future<_i5.PdfBook?>.value(),
          )
          as _i4.Future<_i5.PdfBook?>);

  @override
  _i4.Future<void> insertBook(_i5.PdfBook? book) =>
      (super.noSuchMethod(
            Invocation.method(#insertBook, [book]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> updateBook(_i5.PdfBook? book) =>
      (super.noSuchMethod(
            Invocation.method(#updateBook, [book]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> deleteBook(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteBook, [id]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [BookmarkLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockBookmarkLocalDataSource extends _i1.Mock
    implements _i6.BookmarkLocalDataSource {
  MockBookmarkLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i7.Bookmark>> getAllBookmarks() =>
      (super.noSuchMethod(
            Invocation.method(#getAllBookmarks, []),
            returnValue: _i4.Future<List<_i7.Bookmark>>.value(<_i7.Bookmark>[]),
          )
          as _i4.Future<List<_i7.Bookmark>>);

  @override
  _i4.Future<_i7.Bookmark?> getBookmarkById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getBookmarkById, [id]),
            returnValue: _i4.Future<_i7.Bookmark?>.value(),
          )
          as _i4.Future<_i7.Bookmark?>);

  @override
  _i4.Future<List<_i7.Bookmark>> getBookmarksByPdfId(String? pdfBookId) =>
      (super.noSuchMethod(
            Invocation.method(#getBookmarksByPdfId, [pdfBookId]),
            returnValue: _i4.Future<List<_i7.Bookmark>>.value(<_i7.Bookmark>[]),
          )
          as _i4.Future<List<_i7.Bookmark>>);

  @override
  _i4.Future<void> insertBookmark(_i7.Bookmark? bookmark) =>
      (super.noSuchMethod(
            Invocation.method(#insertBookmark, [bookmark]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> updateBookmark(_i7.Bookmark? bookmark) =>
      (super.noSuchMethod(
            Invocation.method(#updateBookmark, [bookmark]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> deleteBookmark(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteBookmark, [id]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [Talker].
///
/// See the documentation for Mockito's code generation for more information.
class MockTalker extends _i1.Mock implements _i2.Talker {
  MockTalker() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.TalkerSettings get settings =>
      (super.noSuchMethod(
            Invocation.getter(#settings),
            returnValue: _FakeTalkerSettings_0(
              this,
              Invocation.getter(#settings),
            ),
          )
          as _i2.TalkerSettings);

  @override
  _i4.Stream<_i2.TalkerData> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i4.Stream<_i2.TalkerData>.empty(),
          )
          as _i4.Stream<_i2.TalkerData>);

  @override
  List<_i2.TalkerData> get history =>
      (super.noSuchMethod(
            Invocation.getter(#history),
            returnValue: <_i2.TalkerData>[],
          )
          as List<_i2.TalkerData>);

  @override
  _i2.TalkerFilter get filter =>
      (super.noSuchMethod(
            Invocation.getter(#filter),
            returnValue: _FakeTalkerFilter_1(this, Invocation.getter(#filter)),
          )
          as _i2.TalkerFilter);

  @override
  set settings(_i2.TalkerSettings? value) => super.noSuchMethod(
    Invocation.setter(#settings, value),
    returnValueForMissingStub: null,
  );

  @override
  void configure({
    _i2.TalkerLogger? logger,
    _i2.TalkerSettings? settings,
    _i2.TalkerObserver? observer,
    _i2.TalkerFilter? filter,
    _i2.TalkerErrorHandler? errorHandler,
    _i2.TalkerHistory? history,
  }) => super.noSuchMethod(
    Invocation.method(#configure, [], {
      #logger: logger,
      #settings: settings,
      #observer: observer,
      #filter: filter,
      #errorHandler: errorHandler,
      #history: history,
    }),
    returnValueForMissingStub: null,
  );

  @override
  void handle(Object? exception, [StackTrace? stackTrace, dynamic msg]) =>
      super.noSuchMethod(
        Invocation.method(#handle, [exception, stackTrace, msg]),
        returnValueForMissingStub: null,
      );

  @override
  void log(
    dynamic message, {
    _i2.LogLevel? logLevel = _i2.LogLevel.debug,
    Object? exception,
    StackTrace? stackTrace,
    _i2.AnsiPen? pen,
  }) => super.noSuchMethod(
    Invocation.method(
      #log,
      [message],
      {
        #logLevel: logLevel,
        #exception: exception,
        #stackTrace: stackTrace,
        #pen: pen,
      },
    ),
    returnValueForMissingStub: null,
  );

  @override
  void logTyped(_i2.TalkerLog? log) => super.noSuchMethod(
    Invocation.method(#logTyped, [log]),
    returnValueForMissingStub: null,
  );

  @override
  void logCustom(_i2.TalkerLog? log) => super.noSuchMethod(
    Invocation.method(#logCustom, [log]),
    returnValueForMissingStub: null,
  );

  @override
  void critical(dynamic msg, [Object? exception, StackTrace? stackTrace]) =>
      super.noSuchMethod(
        Invocation.method(#critical, [msg, exception, stackTrace]),
        returnValueForMissingStub: null,
      );

  @override
  void debug(dynamic msg, [Object? exception, StackTrace? stackTrace]) =>
      super.noSuchMethod(
        Invocation.method(#debug, [msg, exception, stackTrace]),
        returnValueForMissingStub: null,
      );

  @override
  void error(dynamic msg, [Object? exception, StackTrace? stackTrace]) =>
      super.noSuchMethod(
        Invocation.method(#error, [msg, exception, stackTrace]),
        returnValueForMissingStub: null,
      );

  @override
  void info(dynamic msg, [Object? exception, StackTrace? stackTrace]) =>
      super.noSuchMethod(
        Invocation.method(#info, [msg, exception, stackTrace]),
        returnValueForMissingStub: null,
      );

  @override
  void verbose(dynamic msg, [Object? exception, StackTrace? stackTrace]) =>
      super.noSuchMethod(
        Invocation.method(#verbose, [msg, exception, stackTrace]),
        returnValueForMissingStub: null,
      );

  @override
  void warning(dynamic msg, [Object? exception, StackTrace? stackTrace]) =>
      super.noSuchMethod(
        Invocation.method(#warning, [msg, exception, stackTrace]),
        returnValueForMissingStub: null,
      );

  @override
  void cleanHistory() => super.noSuchMethod(
    Invocation.method(#cleanHistory, []),
    returnValueForMissingStub: null,
  );

  @override
  void enable() => super.noSuchMethod(
    Invocation.method(#enable, []),
    returnValueForMissingStub: null,
  );

  @override
  void disable() => super.noSuchMethod(
    Invocation.method(#disable, []),
    returnValueForMissingStub: null,
  );
}
