// Mocks generated by Mockito 5.4.6 from annotations
// in codium/test/domain/usecases/explain_text_usecase_context_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:codium/domain/models/ai_explanation/explanation.dart' as _i9;
import 'package:codium/domain/models/ai_explanation/search_source.dart' as _i6;
import 'package:codium/domain/models/pdf_reader/bookmark.dart' as _i8;
import 'package:codium/domain/repositories/ai_repository.dart' as _i3;
import 'package:codium/domain/repositories/storage_repository.dart' as _i7;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;
import 'package:talker/talker.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeTalkerSettings_0 extends _i1.SmartFake
    implements _i2.TalkerSettings {
  _FakeTalkerSettings_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTalkerFilter_1 extends _i1.SmartFake implements _i2.TalkerFilter {
  _FakeTalkerFilter_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [IAiRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIAiRepository extends _i1.Mock implements _i3.IAiRepository {
  MockIAiRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<String> explainText({
    required String? text,
    required String? context,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#explainText, [], {
              #text: text,
              #context: context,
            }),
            returnValue: _i4.Future<String>.value(
              _i5.dummyValue<String>(
                this,
                Invocation.method(#explainText, [], {
                  #text: text,
                  #context: context,
                }),
              ),
            ),
          )
          as _i4.Future<String>);

  @override
  _i4.Future<List<_i6.SearchSource>> searchWeb(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#searchWeb, [query]),
            returnValue: _i4.Future<List<_i6.SearchSource>>.value(
              <_i6.SearchSource>[],
            ),
          )
          as _i4.Future<List<_i6.SearchSource>>);
}

/// A class which mocks [IStorageRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIStorageRepository extends _i1.Mock
    implements _i7.IStorageRepository {
  MockIStorageRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i8.Bookmark>> getBookmarksByPdfId(String? pdfId) =>
      (super.noSuchMethod(
            Invocation.method(#getBookmarksByPdfId, [pdfId]),
            returnValue: _i4.Future<List<_i8.Bookmark>>.value(<_i8.Bookmark>[]),
          )
          as _i4.Future<List<_i8.Bookmark>>);

  @override
  _i4.Future<void> saveBookmark(_i8.Bookmark? bookmark) =>
      (super.noSuchMethod(
            Invocation.method(#saveBookmark, [bookmark]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> deleteBookmark(String? bookmarkId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteBookmark, [bookmarkId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i9.Explanation>> getAllExplanations() =>
      (super.noSuchMethod(
            Invocation.method(#getAllExplanations, []),
            returnValue: _i4.Future<List<_i9.Explanation>>.value(
              <_i9.Explanation>[],
            ),
          )
          as _i4.Future<List<_i9.Explanation>>);

  @override
  _i4.Future<List<_i9.Explanation>> getExplanationsByPdfId(String? pdfId) =>
      (super.noSuchMethod(
            Invocation.method(#getExplanationsByPdfId, [pdfId]),
            returnValue: _i4.Future<List<_i9.Explanation>>.value(
              <_i9.Explanation>[],
            ),
          )
          as _i4.Future<List<_i9.Explanation>>);

  @override
  _i4.Future<void> saveExplanation(_i9.Explanation? explanation) =>
      (super.noSuchMethod(
            Invocation.method(#saveExplanation, [explanation]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> deleteExplanation(String? explanationId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteExplanation, [explanationId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i9.Explanation>> searchExplanations(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#searchExplanations, [query]),
            returnValue: _i4.Future<List<_i9.Explanation>>.value(
              <_i9.Explanation>[],
            ),
          )
          as _i4.Future<List<_i9.Explanation>>);
}

/// A class which mocks [Talker].
///
/// See the documentation for Mockito's code generation for more information.
class MockTalker extends _i1.Mock implements _i2.Talker {
  MockTalker() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.TalkerSettings get settings =>
      (super.noSuchMethod(
            Invocation.getter(#settings),
            returnValue: _FakeTalkerSettings_0(
              this,
              Invocation.getter(#settings),
            ),
          )
          as _i2.TalkerSettings);

  @override
  _i4.Stream<_i2.TalkerData> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i4.Stream<_i2.TalkerData>.empty(),
          )
          as _i4.Stream<_i2.TalkerData>);

  @override
  List<_i2.TalkerData> get history =>
      (super.noSuchMethod(
            Invocation.getter(#history),
            returnValue: <_i2.TalkerData>[],
          )
          as List<_i2.TalkerData>);

  @override
  _i2.TalkerFilter get filter =>
      (super.noSuchMethod(
            Invocation.getter(#filter),
            returnValue: _FakeTalkerFilter_1(this, Invocation.getter(#filter)),
          )
          as _i2.TalkerFilter);

  @override
  set settings(_i2.TalkerSettings? value) => super.noSuchMethod(
    Invocation.setter(#settings, value),
    returnValueForMissingStub: null,
  );

  @override
  void configure({
    _i2.TalkerLogger? logger,
    _i2.TalkerSettings? settings,
    _i2.TalkerObserver? observer,
    _i2.TalkerFilter? filter,
    _i2.TalkerErrorHandler? errorHandler,
    _i2.TalkerHistory? history,
  }) => super.noSuchMethod(
    Invocation.method(#configure, [], {
      #logger: logger,
      #settings: settings,
      #observer: observer,
      #filter: filter,
      #errorHandler: errorHandler,
      #history: history,
    }),
    returnValueForMissingStub: null,
  );

  @override
  void handle(Object? exception, [StackTrace? stackTrace, dynamic msg]) =>
      super.noSuchMethod(
        Invocation.method(#handle, [exception, stackTrace, msg]),
        returnValueForMissingStub: null,
      );

  @override
  void log(
    dynamic message, {
    _i2.LogLevel? logLevel = _i2.LogLevel.debug,
    Object? exception,
    StackTrace? stackTrace,
    _i2.AnsiPen? pen,
  }) => super.noSuchMethod(
    Invocation.method(
      #log,
      [message],
      {
        #logLevel: logLevel,
        #exception: exception,
        #stackTrace: stackTrace,
        #pen: pen,
      },
    ),
    returnValueForMissingStub: null,
  );

  @override
  void logTyped(_i2.TalkerLog? log) => super.noSuchMethod(
    Invocation.method(#logTyped, [log]),
    returnValueForMissingStub: null,
  );

  @override
  void logCustom(_i2.TalkerLog? log) => super.noSuchMethod(
    Invocation.method(#logCustom, [log]),
    returnValueForMissingStub: null,
  );

  @override
  void critical(dynamic msg, [Object? exception, StackTrace? stackTrace]) =>
      super.noSuchMethod(
        Invocation.method(#critical, [msg, exception, stackTrace]),
        returnValueForMissingStub: null,
      );

  @override
  void debug(dynamic msg, [Object? exception, StackTrace? stackTrace]) =>
      super.noSuchMethod(
        Invocation.method(#debug, [msg, exception, stackTrace]),
        returnValueForMissingStub: null,
      );

  @override
  void error(dynamic msg, [Object? exception, StackTrace? stackTrace]) =>
      super.noSuchMethod(
        Invocation.method(#error, [msg, exception, stackTrace]),
        returnValueForMissingStub: null,
      );

  @override
  void info(dynamic msg, [Object? exception, StackTrace? stackTrace]) =>
      super.noSuchMethod(
        Invocation.method(#info, [msg, exception, stackTrace]),
        returnValueForMissingStub: null,
      );

  @override
  void verbose(dynamic msg, [Object? exception, StackTrace? stackTrace]) =>
      super.noSuchMethod(
        Invocation.method(#verbose, [msg, exception, stackTrace]),
        returnValueForMissingStub: null,
      );

  @override
  void warning(dynamic msg, [Object? exception, StackTrace? stackTrace]) =>
      super.noSuchMethod(
        Invocation.method(#warning, [msg, exception, stackTrace]),
        returnValueForMissingStub: null,
      );

  @override
  void cleanHistory() => super.noSuchMethod(
    Invocation.method(#cleanHistory, []),
    returnValueForMissingStub: null,
  );

  @override
  void enable() => super.noSuchMethod(
    Invocation.method(#enable, []),
    returnValueForMissingStub: null,
  );

  @override
  void disable() => super.noSuchMethod(
    Invocation.method(#disable, []),
    returnValueForMissingStub: null,
  );
}
